services:
  precision_scraper:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: my-precision_scraper-app:latest
    container_name: precision_scraper
    ports:
      - "3000:3000"
    volumes:
      - data:/app/data
      - lib:/app/lib
    restart: unless-stopped

volumes:
  data:
    name: precision_scraper_data
  lib:
    name: precision_scraper_lib
