name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build-test-format:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        crystal: [latest]
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Tests
        run: make test

      - name: Check Formatting
        run: crystal tool format --check
